version: "3"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.3.7
    restart: always
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mariauser
      - MYSQL_PASSWORD=password
    volumes:
      - ./configs/mariadb/my.cnf:/etc/mysql/my.cnf
      - ./configs/mariadb/init:/docker-entrypoint-initdb.d
    user: mysql
    ports:
      - 3306:3306
