version: "3"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.3.7
    restart: always
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mariauser
      - MYSQL_PASSWORD=password
    volumes:
      - ./configs/mariadb/my.cnf:/etc/mysql/my.cnf
      - ./configs/mariadb/init:/docker-entrypoint-initdb.d
    user: mysql
    ports:
      - 3306:3306

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2022-01-08T03-11-54Z
    restart: always
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=TpD46gwKTZ7mzcuEw5voVR7
    ports:
      - 9000:9000
      - 9003:9003
    command: server /data --console-address ":9003"
